---
name: CICD-1
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from GitHub"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test The Container
        run: echo "Testing The Container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
